title: Sippy Cup
description: A wireframe system for quick HTML/SASS prototypes
  
markdown: redcarpet
highlighter: pygments
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

baseurl: '/'
port: 4000
url: //davidwells.highchairdesign.com


twitter_handle: 

# Permalink Configuration
permalink: /blog/:year/:month/:title

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'node_modules', 'Procfile', 'feed.xml']

#Setting relative permalink to false. See http://jekyllrb.com/docs/upgrading/.
relative_permalinks: false

sass:
  sass_dir: _sass